trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - release-*

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: build
    type: github
    name: Umbraco/Umbraco.Build
    endpoint: umbraco

parameters:
  - name: cache_nuget
    displayName: Cache NuGet packages
    type: boolean
    default: false # Disabled by default due to MyGet allowing version overwrite, which can cause issues with cached packages from previous runs
  - name: prerelease
    displayName: Prerelease
    type: string
    default: auto
    values:
      - auto # Only release to MyGet on public releases, otherwise skip
      - prerelease # Release to MyGet pre-release feed, regardless of release type
      - nightly # Release to MyGet nightly feed, regardless of release type
      - skip # Skip releasing to MyGet, regardless of release type
  - name: release
    displayName: Release
    type: string
    default: auto
    values:
      - auto # Only release to NuGet on public releases, otherwise skip
      - public # Release to NuGet, regardless of release type
      - skip # Skip releasing to NuGet, regardless of release type
  - name: sbom_generate
    displayName: Generate SBOM
    type: boolean
    default: false # SBOM is still generated for release/hotfix branches and release-* tags

extends:
  template: devops/templates/azure-pipelines-template.yml@build
  parameters:
    product_name: "Umbraco.StorageProviders"
    run_tests: skip # This repo has no tests
    cache_nuget: ${{ parameters.cache_nuget }}
    prerelease: ${{ parameters.prerelease }}
    release: ${{ parameters.release }}
    sbom_generate: ${{ parameters.sbom_generate }}
    sbom_dt_variable_group: 'dependency-track'
